
# Joystick buttons
BUTTON_DISC     = 7
BUTTON_ACC      = BUTTON_DISC - 0
BUTTON_ROTR     = BUTTON_DISC - 1
BUTTON_REV      = BUTTON_DISC - 2
BUTTON_ROTL     = BUTTON_DISC - 3
BUTTON_LEFT     = BUTTON_DISC - 4
BUTTON_RIGHT    = BUTTON_DISC - 5


